src/Entity/Facture.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FactureRepository")
 */
class Facture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(0, message = "Un identifiant supérieur à {{ value }}.")
     * @Assert\Regex(pattern="/^[0-9]{1,4}$/", message="Entre 1 et 4 chiffres.")
     */
    private $client_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Ip(message = "Ce n'est pas une adresse IP valide.")
     */
    private $client_adresse_ip;

    /**
     * @ORM\Column(type="float")
     */
    private $montant_ht;

    /**
     * @ORM\Column(type="float")
     */
    private $montant_tva;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual("01/01/2020", message = "La date ne peut pas être inférieure à {{ compared_value }}!")
     * @Assert\LessThanOrEqual("today", message = "La date ne peut pas être supérieure à aujourd'hui!")
     */
    private $facture_createAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?int
    {
        return $this->client_id;
    }

    public function setClientId(int $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getClientAdresseIp(): ?string
    {
        return $this->client_adresse_ip;
    }

    public function setClientAdresseIp(string $client_adresse_ip): self
    {
        $this->client_adresse_ip = $client_adresse_ip;

        return $this;
    }

    public function getMontantHt(): ?float
    {
        return $this->montant_ht;
    }

    public function setMontantHt(float $montant_ht): self
    {
        $this->montant_ht = $montant_ht;

        return $this;
    }

    public function getMontantTva(): ?float
    {
        return $this->montant_tva;
    }

    public function setMontantTva(float $montant_tva): self
    {
        $this->montant_tva = $montant_tva;

        return $this;
    }

    public function getFactureCreateAt(): ?\DateTimeInterface
    {
        return $this->facture_createAt;
    }

    public function setFactureCreateAt(\DateTimeInterface $facture_createAt): self
    {
        $this->facture_createAt = $facture_createAt;

        return $this;
    }
}

src/Form/FactureType.php
<?php

namespace App\Form;

use App\Entity\Facture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;

class FactureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('client_id', IntegerType::class, [
                'help' => 'Un nombre entier de 4 chiffres',
            ])
            ->add('client_adresse_ip', TextType::class, [
                'help' => 'Une adresse IP normalisée ex: 192.168.0.xxx'
            ])
            ->add('montant_ht', MoneyType::class, [
                'currency' => false
            ])
            ->add('montant_tva', PercentType::class, [
                'scale' => 2,
                'symbol' => false,
                'help' => 'Séparateur décimal à utiliser "."',
            ])
            ->add('facture_createAt', DateType::class, [
                'widget' => 'single_text',
                'html5' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Facture::class,
        ]);
    }
}

src/Controller/FactureController.php
<?php

namespace App\Controller;


use App\Entity\Facture;
use App\Form\FactureType;
use App\Repository\FactureRepository;
use App\Service\Facture\FactureService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class FactureController extends AbstractController
{
    private $entityManager;
    private $factureRepository;

    public function __construct(EntityManagerInterface $entityManager, FactureRepository $factureRepository)
    {
        // initialisation de l entityManager
        $this->entityManager = $entityManager;
        // initialisation du Repository Facture
        $this->factureRepository = $factureRepository;
    }

    /**
     * @Route("/", name="app_facture", methods={"GET"})
     */
    public function index(): Response
    {
        // appelle de la methode du Repository qui retourne toutes les Factures
        $factureList = $this->factureRepository->findAll();
        return $this->render('facture/index.html.twig', [
            'title' => 'Liste des factures',
            'factureList' => $factureList,
        ]);
    }

    /**
     * appelle de la page de creation d une facture
     * 
     * @Route("/facture/create", name="app_create_facture", methods={"GET", "POST"})
     * @param Request $request
     * @return Response
     */
    public function createFacture(Request $request): Response
    {
        // instanciation d un nouvel objet Facture
        $facture = new Facture;
        // recuperation du builder du formulaire associe a l entity Facture
        $factureForm = $this->createForm(FactureType::class, $facture);
        $factureForm->handleRequest($request);
        // formulaire soumis et valide
        if ($factureForm->isSubmitted() && $factureForm->isValid()) {
            // persistence des donnees
            $this->entityManager->persist($facture);
            $this->entityManager->flush();
            // redirige vers la page des factures
            return $this->redirectToRoute('app_facture');
        }
        // sinon on affiche le formulaire
        return $this->render('facture/create.html.twig', [
            'title' => 'Création de la facture',
            'form' => $factureForm->createView()
        ]);
    }

    /**
     * @Route("/facture_pdf/{id}", name="app_facture_pdf", methods={"GET"})
     * 
     * @param FactureService    le service associe a la gestion des factures
     * @param Integer   le numero identifiant de la facture selectionnee
     */
    public function generatePdf(FactureService $factureService, int $id)
    {
        $factureService->getPDF($id);
        exit;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="shortcut icon" href="{{ asset('build/images/favicon.ico') }}">
        {% block stylesheets %}
        {# 'app' must match the first argument to addEntry() in webpack.config.js #}
        {{ encore_entry_link_tags('app') }}

        <!-- Renders a link tag (if your module requires any CSS)
                            <link rel="stylesheet" href="/build/app.css"> -->
        {% endblock %}
    </head>

    <body>
        <!-- header area -->
        {% block header %}
        <header>
            <!-- navbar area -->
            {% include('include/header.html.twig') %}
            <!-- /navbar area -->
        </header>
        {% endblock %}
        <!-- /header area -->

        <!-- body area -->
        {% block body %}
        {% endblock %}
        <!-- body area -->

        <!-- footer area -->
        {% block footer %}
        {% include('include/footer.html.twig') %}
        {% endblock %}
        <!-- ./footer area -->
        {% block javascripts %}
        {{ encore_entry_script_tags('app') }}

        <!-- Renders app.js & a webpack runtime.js file
                            <script src="/build/runtime.js"></script>
                            <script src="/build/app.js"></script> -->
        {% endblock %}
    </body>

</html>

templates/facture/_form.html.twig
<!-- elements du formulaire -->
{{ form_start(form) }}

<!-- debut des champs pour la saisie -->
<div class="col-sm-8 mx-auto">

    <!-- numero identifiant du client -->
    <div class="mb-4">
        {{ form_label(form.client_id, 'N° identifiant du client') }}
        {{ form_widget(form.client_id, {'attr': {'class': 'form-control'}}) }}
        {{ form_help(form.client_id, {
            'help_attr': {'class': 'small text-muted font-italic'}
        }) }}
    </div>
    <!-- /numero identifiant du client -->

    <!-- adresse IP du client -->
    <div class="mb-4">
        {{ form_label(form.client_adresse_ip, 'Adresse IP du paiement') }}
        {{ form_widget(form.client_adresse_ip, {'attr': {'class': 'form-control'}}) }}
        {{ form_help(form.client_adresse_ip, {
            'help_attr': {'class': 'small text-muted font-italic'}
        }) }}
    </div>
    <!-- /adresse IP du client -->

    <!-- montant hors-taxe de la facture -->
    <div class="mb-4">
        {{ form_label(form.montant_ht, 'Montant Hors-Taxe') }}
        {{ form_widget(form.montant_ht, {'attr': {'class': 'form-control'}}) }}
    </div>
    <!-- /montant hors-taxe de la facture -->

    <!-- montant de la TVA -->
    <div class="mb-4">
        {{ form_label(form.montant_tva, 'Montant de la TVA') }}
        {{ form_widget(form.montant_tva, {'attr': {'class': 'form-control'}}) }}
        {{ form_help(form.montant_tva, {
            'help_attr': {'class': 'small text-muted font-italic'}
        }) }}
    </div>
    <!-- /montant de la TVA -->

    <!-- date de la facture -->
    <div class="mb-4">
        {{ form_label(form.facture_createAt, 'Date du paiement') }}
        {{ form_widget(form.facture_createAt, {'attr': {'class': 'form-control'}}) }}
    </div>
    <!-- /date de la facture -->

    <!-- bouton de validation du formulaire-->
    <button class="btn btn-primary btn-block mb-5">{{ save_button | default('Save') }}</button>
    <!-- /bouton de validation du formulaire-->
</div>
<!-- /debut des champs pour la saisie -->

{{ form_end(form) }}
<!-- /elements du formulaire -->

templates/facture/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creation facture
{% endblock %}

{% block body %}

<!-- conteneur de la page du formulaire de creation d une facture -->
<div class="container mt-4">
    <!-- titre de la page de l affichage des factures -->
    <div class="py-5 text-center">
        <h1 class="display-4 font-weight-bold text-uppercase">{{ title }}</h1>
    </div>
    <!-- /titre de la page de l affichage des factures -->

    <!-- bouton pour revenir a la page precedente -->
    <div class="">
        <a class="btn btn-info btn-sm" href="/">&laquo;
            {{ back_button | default('Retour') }}</a>
    </div>
    <!-- /bouton pour revenir a la page precedente -->

    <br>
    <!-- include du template de formulaire -->
    {{ include('facture/_form.html.twig', { form: form, save_button: 'Valider', back_button: 'Return'}) }}
    <!-- include du template de formulaire -->
</div>
<!-- /conteneur de la page du formulaire de creation d une facture -->

{% endblock %}

templates/facture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page des factures{% endblock %}

{% block body %}
<!-- conteneur de la page de gestion des factures-->
<div class="container mt-4" id="content-wrap">
    <!-- titre de la page de l affichage des factures -->
    <div class="py-5 text-center">
        <h1 class="display-4 font-weight-bold text-uppercase">{{ title }}</h1>
    </div>
    <!-- /titre de la page de l affichage des factures -->
    <br>
    <!-- bouton pour creer une facture -->
    <div class="mb-3">
        <a class="btn btn-primary btn-lg btn-block" href="{{ path('app_create_facture') }}">Créer une facture</a>
    </div>
    <!-- /bouton pour creer une facture -->

    <!-- si au moins un enregistrement dans la table facture -->
    {% if factureList %}
    <!-- creation d un tableau avec la liste des factures -->
    <table class="table table-striped">
        <!-- entete du tableau -->
        <thead class="thead-light">
            <tr>
                <th scope="col">Identifiant Client</th>
                <th scope="col">Adresse IP</th>
                <th scope="col">Date de la facture</th>
                <th class="text-center" scope="col">Action</th>
            </tr>
        </thead>
        <!-- /entete du tableau -->

        <!-- informations concernant les factures -->
        <tbody>
            <!-- boucle dans le tableau des factures passe en parametre-->
            {% for facture in factureList %}
            <tr>
                <td scope="row"> {{ facture.clientid }}</td>
                <td>{{ facture.clientadresseip }}</td>
                <td>{{ facture.facturecreateAt | date('d:m:Y') }}</td>
                <td>
                    <a class="btn btn-success btn-sm btn-block" href="{{ path('app_facture_pdf', {id: facture.id}) }}"
                        target="_blank">Générer le PDF</a>
                </td>
            </tr>
            {% endfor %}
            <!-- /boucle dans le tableau des factures passe en parametre-->
        </tbody>
        <!-- /informations concernant les factures -->

    </table>
    <!-- /creation d un tableau avec la liste des factures -->

    <!-- sinon affiche un message -->
    {% else %}
    <p>Il n'y a aucune facture pour le moment</p>
    {% endif %}
</div>
<!-- /conteneur de la page de gestion des factures-->
{% endblock %}

templates/facture/pdf.html.twig
<!DOCTYPE html>
<html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Franck Jakubowski">
        <meta name="description" content="Affichage d'une facture au format PDF">

        <title>
            {% block title %}
            Facture n°{{ facture.id }}
            {% endblock %}
        </title>

        {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('build/pdf.css')[1:] }}">
        {% endblock %}
    </head>

    <body>
        {% block body %}

        {# layout for PDF files #}
        <!-- global container -->
        <div class="px-2">

            <!-- header with logo & title -->
            <header>
                <div class="center">
                    {# uncomment the line ;extension=gd2 in the php.in file #}
                    <img class="" src="{{ asset('build/images/logo.png')[1:] }}" height="100"
                         alt="Aucune Commission Logo">
                    <!-- titre de la page du pdf -->
                    <div class="my-5 center">
                        <h1 class="textBold textToUpper">{{ title }}</h1>
                    </div>
                </div>
            </header>
            <!-- /header with logo & title -->


            <!-- informations et reference de la commande -->
            <table class="mb-5">
                <tbody>
                    <tr>
                        <td></td>
                        <!-- informations & references de la facture -->
                        <td class="td-vertical-align" width="40%">
                            <div class="td-border-dark">
                                <div class="td-bg-dark rounded p-2 font-weight-bold">
                                    Informations commande
                                </div>
                                <div class="interline pb-2 px-2">
                                    <p>Numéro de facture: {{ facture.id }}</p>
                                    <p>Numéro client: {{ facture.clientid }}</p>
                                    <p>Adresse IP du paiement: {{ facture.clientAdresseIp }}</p>
                                    <p>Date de la facture:
                                        {{ facture.factureCreateAt | date('d:m:Y') }}
                                    </p>
                                </div>
                            </div>
                        </td>
                        <!-- /informations & references de la facture -->
                    </tr>
                </tbody>
            </table>
            <!-- /informations et reference de la commande -->

            <!-- customer details area -->
            <table>
                <tbody>
                    <tr>
                        <!-- adresse de livraison -->
                        <td class="td-vertical-align">
                            <div class="td-border-blue">
                                <div class="td-bg-blue p-2 font-weight-bold">Client livré</div>
                                <div class="interline pb-2 px-2">
                                    <p>Prénom Nom du client</p>
                                    <p>Adresse du client</p>
                                    <p>Code postal et ville du client</p>
                                </div>
                            </div>
                        </td>
                        <!-- /adresse de livraison -->

                        <td width="30%"></td>

                        <!-- adresse de facturation -->
                        <td class="td-vertical-align">
                            <div class="td-border-blue">
                                <div class="td-bg-blue p-2 font-weight-bold">Client facturé</div>
                                <div class="interline pb-2 px-2">
                                    <p>Prénom Nom du client</p>
                                    <p>Adresse du client</p>
                                    <p>Code postal et ville du client</p>
                                </div>
                            </div>
                        </td>
                        <!-- /adresse de facturation -->
                    </tr>
                </tbody>
            </table>
            <!-- /customer details area -->

            <br>

            <!-- main table -->
            <table class="table-striped mb-5">
                <tbody>
                    <thead>
                        <!-- ligne de l entete du tableau -->
                        <tr>
                            <!-- description de la commande -->
                            <th class="td-vertical-align" width="80%">
                                <div class="td-bg-red p-2 font-weight-bold">
                                    Description
                                </div>
                            </th>
                            <!-- /description de la commande -->

                            <!-- montant de la facture -->
                            <th class="td-vertical-align text-right" width="20%">
                                <div class="td-bg-dark p-2 font-weight-bold">
                                    {{ ((1 + facture.montantTva) * facture.montantHt) | number_format(2) }} €
                                </div>
                            </th>
                            <!-- /montant de la facture -->
                        </tr>
                        <!-- /ligne de l entete du tableau -->
                    </thead>

                    <!-- ligne concernant 1 article -->
                    {# si plusieurs articles boucle pour pour remplir la table #}
                    <tr>
                        <td class="td-vertical-align">
                            <p class="p-1">Lorem ipsum dolor sit amet, consectetur
                                adipisicing elit. Voluptatum corrupti, velit dignissimos ut aut delectus doloremque
                                dolores
                                voluptates in atque eum reiciendis vero iusto et praesentium eaque dolor ducimus
                                optio.</p>
                        </td>
                        <td class="td-vertical-align text-right">
                            <p class="p-1">{{ facture.montantHt | number_format(2)}} €</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-vertical-align">
                            <p class="p-1">oc tu nunc in illo probas. Qua tu etiam inprudens utebare non numquam.</p>
                        </td>
                        <td class="td-vertical-align text-right">
                            <p class="p-1">0 €</p>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-vertical-align">
                            <p class="p-1">Nos cum te, M. Quid sequatur, quid repugnet, vident.</p>
                        </td>
                        <td class="td-vertical-align text-right">
                            <p class="p-1">0 €</p>
                        </td>
                    </tr>
                    {# /si plusieurs articles boucle pour pour remplir la table #}
                    <!-- /ligne de concernant 1 article -->
                </tbody>

                <!-- TVA, TTC -->
                <tfoot>
                    <tr>
                        <td class="text-right tfoot-border-bottom">
                            TOTAL HT
                        </td>
                        <td class="text-right table-warning tfoot-border-bottom">
                            {{ facture.montantHt | number_format(2) }} €
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right tfoot-border-bottom">
                            TVA à {{ facture.montantTva * 100 }} %
                        </td>
                        <td class="text-right table-warning tfoot-border-bottom">
                            {{ (facture.montantTva * facture.montantHt) | number_format(2) }} €
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right tfoot-border-bottom">
                            <strong>TOTAL TTC À PAYER</strong>
                        </td>
                        <td class="text-right table-warning tfoot-border-bottom">
                            <strong>{{ ((1 + facture.montantTva) * facture.montantHt) | number_format(2) }} €</strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right">
                            <em>Moyens de paiement</em>
                        </td>
                        <td class="center table-warning">
                            <em>Comptant</em>
                        </td>
                    </tr>
                </tfoot>
                <!-- /TVA, TTC -->
            </table>
            <!-- main table -->

            <!-- informations commerciales -->
            <table class="mb-5">
                <tbody>
                    <tr>
                        <!-- contact & horaires -->
                        <td class="td-vertical-align" width="40%">
                            <div class="td-border-dark">
                                <div class="td-bg-dark p-2 font-weight-bold">
                                    Contact
                                </div>
                                <div class="center interline pb-2 px-2">
                                    <p><a href="https://google.fr">Sevice client</a></p>
                                    <p>Du lundi au vendredi de 10h à 15h</p>
                                    <p><strong>09 75 18 04 34</strong></p>
                                    <p>info@aucunecommission.com</p>
                                </div>
                            </div>
                        </td>
                        <!-- /contact & horaires -->
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <!-- informations commerciales -->

            <!-- global container -->

            {% endblock %}

            <!-- conteneur fixe-->
            {% block javascripts %}
            <script src="{{ asset('/build/app.js')[1:] }}"></script>
            {% endblock %}
    </body>

</html>

templates/include/footer.html.twig
<footer class="d-flex flex-column flex-md-column text-center" id="footer">
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="#">Nous trouver</a>
        </li>
        <li class="list-inline-item">
            <a href="#">Conditions d'utilisation</a>
        </li>
        <li class="list-inline-item">
            <a href="#">Politique de confidentialité</a>
        </li>
        <li class="list-inline-item">
            <a href="#">Contact</a>
        </li>
    </ul>
    <p><br>&copy;
        {{ 'now'|date('Y') }}
        - CCI Developpement</p>
</footer>

templates/include/header.html.twig
<!-- main navigation -->
<nav class="navbar navbar-expand-lg bg-white shadow fixed-top py-0 mb-4">
    <div class="container justify-content-center">
        <!-- navbar brand & logo -->
        <a class="navbar-brand" href="/">
            <img class="d-inline-block align-center" src="{{ asset('build/images/logo.png') }}" height="100"
                alt="Aucune Commission Logo">
        </a>
        <!-- /navbar brand & logo -->
    </div>
</nav>
<!-- /main navigation -->